name: Sender

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  send:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: call api via curl
        run: |
         curl \
         -X POST \
         -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
         -H "Accept: application/vnd.github.v3+json" \
         https://api.github.com/repos/ntt-training/github-actions/dispatches \
         -d '{"event_type":"receive-test", "client_payload": {"body": "This is world!"}}'
